//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_home_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountItem
    {
        public int accountItemId { get; set; }
        public string typeOfItem { get; set; }
        public decimal singlePrice { get; set; }
        public int itemQuantity { get; set; }
        public string showRoom { get; set; }
        public int accountId { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
