//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_home_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int itemId { get; set; }
        public int itemCode { get; set; }
        public string itemName { get; set; }
        public string countryOfOrigin { get; set; }
        public int productionYear { get; set; }
        public decimal itemPrice { get; set; }
        public int showRoomQuantity { get; set; }
        public string showRoomName { get; set; }
        public int typeOfItem { get; set; }
        public byte[] pictureOfItem { get; set; }
    
        public virtual ItemCategory ItemCategory { get; set; }
    }
}
