//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_home_furniture.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Showroom
    {
        public int showRoomId { get; set; }
        public string showRoomName { get; set; }
        public string Owner { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string e_mail { get; set; }
        public string web_Site { get; set; }
        public int taxId { get; set; }
        public string bankAccountNumber { get; set; }
    }
}
